[project]
name = "vplace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.17",
    "django-types>=0.24.0",
    "djangorestframework>=3.18.0",
    "google-genai>=2.19.0",
    "pymupdf>=1.28.2",
    "python-dotenv>=1.2.3",
]

[project.scripts]
vplace = "vplace:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.pyrefly]
search-path = ["backend"]

[tool.pyright]
extraPaths = ["backend"]
