# Generated by Django 5.2.17 on 2026-09-17 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('resume_analyzer', '0001_initial'),
        ('resumes', '0003_resume_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeJDMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_match', models.IntegerField()),
                ('technical_match', models.IntegerField()),
                ('experience_match', models.IntegerField()),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_matches', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jd_matches', to='resumes.resume')),
            ],
        ),
    ]
