# Generated by Django 5.2.17 on 2026-08-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
